services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
      - backend
      - frontend
    restart: unless-stopped

  backend:
    env_file: .env
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        GROUP_ID: ${GROUP_ID}
        GROUP_NAME: ${GROUP_NAME}
        USER_ID: ${USER_ID}
        USER_NAME: ${USER_NAME}
    container_name: backend
    ports:
      - "3001:3001"
    restart: unless-stopped

  frontend:
    env_file: .env
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        GROUP_ID: ${GROUP_ID}
        GROUP_NAME: ${GROUP_NAME}
        USER_ID: ${USER_ID}
        USER_NAME: ${USER_NAME}
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

  prometheus:
    env_file: ".env"
    build:
      context: ./monitoring/prometheus
      dockerfile: Dockerfile
      args:
        GROUP_ID: ${GROUP_ID}
        GROUP_NAME: ${GROUP_NAME}
        USER_ID: ${USER_ID}
        USER_NAME: ${USER_NAME}
    container_name: prometheus
    ports:
      - "9090:9090"
    depends_on:
      - cadvisor
    restart: unless-stopped

  grafana:
    env_file: ".env"
    build:
      context: ./monitoring/grafana
      dockerfile: Dockerfile
      args:
        GROUP_ID: ${GROUP_ID}
        GROUP_NAME: ${GROUP_NAME}
        USER_ID: ${USER_ID}
        USER_NAME: ${USER_NAME}
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    restart: unless-stopped

  alertmanager:
    env_file: ".env"
    build:
      context: ./monitoring/alertmanager
      dockerfile: Dockerfile
      args:
        GROUP_ID: ${GROUP_ID}
        GROUP_NAME: ${GROUP_NAME}
        USER_ID: ${USER_ID}
        USER_NAME: ${USER_NAME}
    container_name: alertmanager
    ports:
      - "9093:9093"
    depends_on:
      - prometheus
    restart: unless-stopped
