global:
  scrape_interval: 10s

  external_labels:
    monitor: "Don.Monitorinio"

scrape_configs:
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets:
          - cadvisor:8080
