global:
  scrape_interval: 10s

  external_labels:
    monitor: "Don.Monitorinio"

scrape_configs:
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets:
          - cadvisor:8080

  - job_name: "prometheus"
    static_configs:
      - targets:
          - localhost:9090

rule_files:
  - alert.rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093
