global:
  scrape_interval: 10s

  external_labels:
    monitor: "Don.Monitorinio"


scrape_configs:
- job_name: frontend
  scrape_interval: 5s
  static_configs:
  - targets:
    - frontend:9090
- job_name: backend
  scrape_interval: 5s
  static_configs:
  - targets:
    - backend:3001